name: datapath_py02
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pandas=1.4.4
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipython
  - ydata-profiling
  - pip:
    - fastapi
    - "uvicorn[standard]"