name: datapath_mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - requests
  - pip
  - pandas=1.5.3
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipython
  - ydata-profiling
  - mlflow=2.2.0
  - hyperopt
  - hydra-core=1.3.2
  - pip:
      - hydra-joblib-launcher==1.2.0